<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign In</name>
   <tag></tag>
   <elementGuidId>beb72536-3d5c-466e-8673-96525da85fc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.w-100.mb-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[text()='Sign In']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fff71a73-2f37-44f5-b7bb-2764ee641a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary w-100 mb-3</value>
      <webElementGuid>77a2df92-08bc-4840-af07-1e228949fe9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>eb0d5b6a-a0bf-46e7-a04c-78c4c3cda5c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>e4eee45d-971b-40c9-ac06-57e7d26024c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;container-fluid bg-300 dark__bg-1200&quot;]/div[@class=&quot;row flex-center position-relative min-vh-100 g-0 py-5&quot;]/div[@class=&quot;col-11 col-sm-10 col-xl-8&quot;]/div[@class=&quot;card border border-200 auth-card&quot;]/div[@class=&quot;card-body pe-md-0&quot;]/div[@class=&quot;row align-items-center gx-0 gy-7&quot;]/div[@class=&quot;col mx-auto&quot;]/form[1]/div[@class=&quot;auth-form-box&quot;]/button[@class=&quot;btn btn-primary w-100 mb-3&quot;]</value>
      <webElementGuid>9965eda4-884d-4710-887a-ed3788cd26d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>4ac6a15d-a7f2-442e-827e-60d96021a355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='top']/div/div[2]/div/div/div/div/div/form/div/button</value>
      <webElementGuid>25497b4f-b403-4cf9-837b-c24ab8f4c840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>068f1b51-e617-4f2c-a1d3-f3355bfaf636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address'])[1]/following::button[1]</value>
      <webElementGuid>039e2176-6f24-4d93-9141-e6453cbfbc5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>62c64b75-35c5-4808-af9a-781b64376782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>9f1036f2-bfcc-4044-855d-08402ee21331</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
