<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_BTMS</name>
   <tag></tag>
   <elementGuidId>76958017-4f75-4393-b87d-063614de162f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navbarDefault']/div/div/a/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.logo-text.ms-2.d-none.d-sm-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e0324fac-e967-4492-b452-3145c8a36548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo-text ms-2 d-none d-sm-block</value>
      <webElementGuid>9c2c8ba5-7d91-4ff9-863a-5173a8684196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BTMS</value>
      <webElementGuid>fa20ea58-2db7-42f0-a0f5-abb06b37854c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarDefault&quot;)/div[@class=&quot;collapse navbar-collapse justify-content-between&quot;]/div[@class=&quot;navbar-logo&quot;]/a[@class=&quot;navbar-brand me-1 me-sm-3&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/p[@class=&quot;logo-text ms-2 d-none d-sm-block&quot;]</value>
      <webElementGuid>8c44b53a-3c8b-43fd-b5de-7c1b22c029a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbarDefault']/div/div/a/div/div/p</value>
      <webElementGuid>7be6c3d5-2310-4606-bd63-2257f65ed5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/preceding::p[1]</value>
      <webElementGuid>a74a3f5a-e35d-4184-a90d-fa8bc5f5419e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[2]/preceding::p[1]</value>
      <webElementGuid>b0a9185b-ce52-47de-9168-52b972279a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>c815ccc6-7cba-44db-9fd6-63b9a4fb1f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'BTMS' or . = 'BTMS')]</value>
      <webElementGuid>56880fbb-46a7-4c3b-b300-ad3c30531071</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
